name: "dla"
platform: "onnxruntime_onnx"

input [
    {
        name: "image"
        data_type: TYPE_UINT8
        dims: [3,1000,1000]
    }
]

output [
    {
        name: "pred_box"
        data_type: TYPE_FP32
        dims: [-1,-1]
    },
    {
        name: "pred_class"
        data_type: TYPE_INT64
        dims: [-1]
    }
]

instance_group [
    {
        kind: KIND_GPU
    }
]